RUNNING_ON = "UBUNTU" #WINDOWS-UBUNTU
databasedriver = "pymysql" #pymysql - mysqlconnector
server = "localhost"
port = 3306
databasename = "aitrader"
user = "root"
pwd = "Pknrp2h8#"
path = "/home/carlosconti/aitrader/basicscraping"
# path = "/home/ubuntucontisola/aitrader/basicscraping/basicscraping "
# path = "C:\\Users\\Carlos Conti\\PycharmProjects\\basicscraping"
pathchromedriver = "/home/carlosconti/aitrader/chromedriver"
pathfirefoxdriver = "/home/carlosconti/aitrader/geckodriver"