RUNNING_ON = "WINDOWS" #WINDOWS-UBUNTU
databasedriver = "pymysql" #pymysql - mysqlconnector
server = "localhost"
port = 3306
databasename = "aitrader"
user = "root"
pwd = "dtisat"
path = "/home/carloscz25_gmail_com/aitrader/basicscraping"
# path = "/home/ubuntucontisola/aitrader/basicscraping/basicscraping "
# path = "C:\\Users\\Carlos Conti\\PycharmProjects\\basicscraping"
pathchromedriver = "/home/carloscz25_gmail_com/aitrader/chromedriver"